# Generated by Django 3.2.9 on 2022-01-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionWithOneAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField(unique=True)),
                ('right_answer', models.CharField(max_length=100)),
                ('wrong_answer_1', models.CharField(max_length=100)),
                ('wrong_answer_2', models.CharField(max_length=100)),
                ('wrong_answer_3', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalm_quizes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionWithMultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalm_quizes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseRightOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalm_quizes.quiz')),
            ],
        ),
    ]
