# Generated by Django 3.2.9 on 2022-03-06 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.IntegerField(default=0)),
                ('quiz_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='UserCourseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalm_quizes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('question_text', models.TextField(unique=True)),
                ('right_answer', models.CharField(max_length=100)),
                ('wrong_answer_1', models.CharField(max_length=100)),
                ('wrong_answer_2', models.CharField(max_length=100)),
                ('wrong_answer_3', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalm_quizes.quiz')),
            ],
            options={
                'verbose_name': 'Вопрос с одним вариантом ответа',
                'verbose_name_plural': 'Вопросы с одним вариантом ответа',
            },
        ),
        migrations.CreateModel(
            name='PutInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('question_text', models.TextField(default='')),
                ('text_for_ordering', models.TextField(default='')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalm_quizes.quiz')),
            ],
            options={
                'verbose_name': 'Задание на порядок слов',
                'verbose_name_plural': 'Задания на порядок слов',
            },
        ),
        migrations.CreateModel(
            name='PutInGaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('question_text', models.TextField(unique=True)),
                ('right_answer', models.CharField(default='', max_length=225)),
                ('choices_list', models.CharField(default='', max_length=225)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalm_quizes.quiz')),
            ],
            options={
                'verbose_name': 'Задание на заполнение пропусков',
                'verbose_name_plural': 'Задания для заполнения пропусков',
            },
        ),
    ]
