# Generated by Django 3.2.9 on 2022-01-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalm_quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizes'},
        ),
    ]
