# Generated by Django 3.2.9 on 2022-01-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalm_quizes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chooserightorder',
            options={'verbose_name': 'Задание на порядок слов', 'verbose_name_plural': 'Задания на порядок слов'},
        ),
        migrations.AlterModelOptions(
            name='questionwithmultiplechoice',
            options={'verbose_name': 'Вопрос с несколькими вариантами ответа', 'verbose_name_plural': 'Вопросы с несколькими вариантами ответа'},
        ),
        migrations.AlterModelOptions(
            name='questionwithoneanswer',
            options={'verbose_name': 'Вопрос с одним вариантом ответа', 'verbose_name_plural': 'Вопросы с одним вариантом ответа'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_number',
            field=models.IntegerField(default=0),
        ),
    ]
