# Generated by Django 3.2.9 on 2022-01-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalm_quizes', '0004_auto_20220125_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechoice',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
    ]
