# Generated by Django 3.2.9 on 2022-03-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalm_quizes', '0004_auto_20220307_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextForTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestForText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('question_text', models.TextField(unique=True)),
                ('right_answer', models.CharField(max_length=100)),
                ('wrong_answer_1', models.CharField(max_length=100)),
                ('wrong_answer_2', models.CharField(max_length=100)),
                ('wrong_answer_3', models.CharField(max_length=100)),
                ('top_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalm_quizes.textfortest')),
            ],
        ),
    ]
