# Generated by Django 3.2.9 on 2022-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalm_quizes', '0005_alter_singlechoice_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='putinorder',
            name='text_for_ordering',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='question_text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='putinorder',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='putinorder',
            name='question_text',
            field=models.TextField(default=''),
        ),
    ]
