# Generated by Django 3.2.9 on 2022-03-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalm_quizes', '0005_testfortext_textfortest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfortext',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kalm_quizes.quiz'),
            preserve_default=False,
        ),
    ]
